"""
Compares the CSV exports in data_and_code_export/cache_data_export (the original
NBSS scrape) against poc_backup_restore_pipeline/cache_data_export (the restored
backup scrape) to verify they are structurally identical:

- Total file count matches
- Every CSV in the original has a corresponding CSV in the restored export
- No extra CSVs exist in the restored export
- Row counts match for each CSV
- Column counts match for each CSV
"""

import csv
import os
import unittest

ORIGINAL_DIR = os.path.join(
    os.path.dirname(__file__), "..", "..", "data_and_code_export", "cache_data_export"
)
RESTORED_DIR = os.path.join(os.path.dirname(__file__), "..", "exported_nbss_data")

# Tables with expected row count differences due to transient/runtime data,
# activity after the backup, or metadata generated by the restore process.
# See the README "Note on expected row count differences" for details.
KNOWN_DIFF_TABLES = {
    ("UTIL", "CurrentJobs"),
    ("UTIL", "RemoteAnalysis"),
    ("UTIL", "Routine"),
    ("UTIL", "SecurityAuditTrail"),
    ("UTIL", "SystemStatus"),
    ("UTIL", "TableColumns"),
    ("UTIL", "TableMethod"),
    ("UTIL", "TableProperties"),
}


def _get_csv_info(base_dir):
    """Walk base_dir and return a dict of {(schema, table): (row_count, col_count)}."""
    info = {}
    if not os.path.isdir(base_dir):
        return info
    for entry in os.scandir(base_dir):
        if entry.is_dir():
            for f in os.scandir(entry.path):
                if f.name.endswith(".csv"):
                    table_name = f.name[:-4]
                    with open(f.path, newline="", encoding="utf-8") as csvfile:
                        reader = csv.reader(csvfile)
                        header = next(reader, None)
                        col_count = len(header) if header else 0
                        row_count = sum(1 for _ in reader)
                    info[(entry.name, table_name)] = (row_count, col_count)
    return info


class TestCompareExports(unittest.TestCase):

    @classmethod
    def setUpClass(cls):
        cls.original = _get_csv_info(ORIGINAL_DIR)
        cls.restored = _get_csv_info(RESTORED_DIR)

        if not cls.original:
            raise RuntimeError(
                f"No CSV files found in original directory: {os.path.abspath(ORIGINAL_DIR)}"
            )
        if not cls.restored:
            raise RuntimeError(
                f"No CSV files found in restored directory: {os.path.abspath(RESTORED_DIR)}"
            )

        print(f"\nOriginal CSVs : {len(cls.original)}")
        print(f"Restored CSVs : {len(cls.restored)}")

    def test_file_count_matches(self):
        self.assertEqual(
            len(self.original),
            len(self.restored),
            f"Original has {len(self.original)} CSVs but restored has {len(self.restored)}",
        )

    def test_every_original_has_restored(self):
        missing = set(self.original.keys()) - set(self.restored.keys())
        self.assertFalse(
            missing,
            f"{len(missing)} CSV(s) in original have no match in restored:\n"
            + "\n".join(f"  {s}.{t}" for s, t in sorted(missing)),
        )

    def test_no_extra_restored(self):
        extra = set(self.restored.keys()) - set(self.original.keys())
        self.assertFalse(
            extra,
            f"{len(extra)} CSV(s) in restored have no match in original:\n"
            + "\n".join(f"  {s}.{t}" for s, t in sorted(extra)),
        )

    def test_row_counts_match(self):
        mismatches = []
        known_diffs = []
        common = set(self.original.keys()) & set(self.restored.keys())
        for key in sorted(common):
            orig_rows = self.original[key][0]
            rest_rows = self.restored[key][0]
            if orig_rows != rest_rows:
                entry = (
                    f"  {key[0]}.{key[1]}: original={orig_rows}, restored={rest_rows}"
                )
                if key in KNOWN_DIFF_TABLES:
                    known_diffs.append(entry)
                else:
                    mismatches.append(entry)

        if known_diffs:
            print(
                f"\n{len(known_diffs)} known table(s) have expected row count differences "
                f"(see README for details):\n" + "\n".join(known_diffs)
            )

        self.assertFalse(
            mismatches,
            f"{len(mismatches)} table(s) have UNEXPECTED mismatched row counts:\n"
            + "\n".join(mismatches),
        )

    def test_column_counts_match(self):
        mismatches = []
        common = set(self.original.keys()) & set(self.restored.keys())
        for key in sorted(common):
            orig_cols = self.original[key][1]
            rest_cols = self.restored[key][1]
            if orig_cols != rest_cols:
                mismatches.append(
                    f"  {key[0]}.{key[1]}: original={orig_cols}, restored={rest_cols}"
                )
        self.assertFalse(
            mismatches,
            f"{len(mismatches)} table(s) have mismatched column counts:\n"
            + "\n".join(mismatches),
        )


if __name__ == "__main__":
    unittest.main(verbosity=2)
