"""
Compares the original NBSS playCD CSV export against the tables extracted into
Databricks by 9_scrape_tables/export_app_tables.py, to verify the restored
backup extraction is structurally identical to the playCD scrape:

- Total table count matches
- Every CSV in the playCD export has a corresponding Databricks table
- No extra Databricks tables exist without a matching CSV
- Row counts match for each table
- Column counts match for each table

The playCD export lives on disk as CSVs (one per table, grouped by schema).
The extracted tables live in a Databricks Unity Catalog, named
`<schema>_<table>` in lowercase. Both sides are keyed by that canonical name.

Requires a `.env` in nbss/playcd/poc_backup_restore_pipeline with:
    DATABRICKS_PROFILE, DATABRICKS_HTTP_PATH, CATALOG, SCHEMA
and an authenticated Databricks CLI profile.
"""

import csv
import os
import unittest

from databricks import sql as databricks_sql
from databricks.sdk.core import Config
from dotenv import load_dotenv

_THIS_DIR = os.path.dirname(__file__)

# Original playCD CSV export (one CSV per table, grouped by schema directory).
PLAYCD_DIR = os.path.join(
    _THIS_DIR, "..", "..", "data_and_code_export", "cache_data_export"
)

load_dotenv(os.path.join(_THIS_DIR, "..", ".env"))
DATABRICKS_PROFILE = os.getenv("DATABRICKS_PROFILE", "dev")
DATABRICKS_HTTP_PATH = os.getenv("DATABRICKS_HTTP_PATH")
CATALOG = os.getenv("CATALOG")
SCHEMA = os.getenv("SCHEMA")

# Tables with expected row count differences due to transient/runtime data,
# activity after the backup, or metadata generated by the restore process.
# See the 9_scrape_tables README "Note on expected row count differences".
KNOWN_DIFF_TABLES = {
    "util_currentjobs",
    "util_remoteanalysis",
    "util_routine",
    "util_securityaudittrail",
    "util_systemstatus",
    "util_tablecolumns",
    "util_tablemethod",
    "util_tableproperties",
}


def _canonical_name(schema, table):
    """Databricks table name for a Cache schema/table: <schema>_<table> lowercased."""
    return f"{schema}_{table}".lower()


def _get_csv_info(base_dir):
    """Walk base_dir and return {canonical_name: (row_count, col_count)}."""
    info = {}
    if not os.path.isdir(base_dir):
        return info
    for entry in os.scandir(base_dir):
        if not entry.is_dir():
            continue
        for f in os.scandir(entry.path):
            if not f.name.endswith(".csv"):
                continue
            table_name = f.name[:-4]
            with open(f.path, newline="", encoding="utf-8") as csvfile:
                reader = csv.reader(csvfile)
                header = next(reader, None)
                col_count = len(header) if header else 0
                row_count = sum(1 for _ in reader)
            info[_canonical_name(entry.name, table_name)] = (row_count, col_count)
    return info


def _connect_databricks():
    cfg = Config(profile=DATABRICKS_PROFILE)
    return databricks_sql.connect(
        server_hostname=cfg.host.replace("https://", ""),
        http_path=DATABRICKS_HTTP_PATH,
        credentials_provider=lambda: cfg.authenticate,
    )


def _get_databricks_info(conn):
    """Return {table_name: (row_count, col_count)} for every table in CATALOG.SCHEMA."""
    cursor = conn.cursor()
    cursor.execute(f"SHOW TABLES IN `{CATALOG}`.`{SCHEMA}`")
    table_names = [row.tableName for row in cursor.fetchall() if not row.isTemporary]

    info = {}
    for name in table_names:
        full = f"`{CATALOG}`.`{SCHEMA}`.`{name}`"

        cursor.execute(f"SELECT COUNT(*) FROM {full}")
        row_count = cursor.fetchone()[0]

        # WHERE 1=0 returns column metadata without transferring any rows.
        cursor.execute(f"SELECT * FROM {full} WHERE 1=0")
        col_count = len(cursor.description)

        info[name] = (row_count, col_count)

    cursor.close()
    return info


class TestCompareExports(unittest.TestCase):

    @classmethod
    def setUpClass(cls):
        cls.playcd = _get_csv_info(PLAYCD_DIR)
        if not cls.playcd:
            raise RuntimeError(
                f"No CSV files found in playCD export: {os.path.abspath(PLAYCD_DIR)}"
            )

        if not DATABRICKS_HTTP_PATH or not CATALOG or not SCHEMA:
            raise RuntimeError(
                "Missing Databricks config. Set DATABRICKS_HTTP_PATH, CATALOG and "
                "SCHEMA in nbss/playcd/poc_backup_restore_pipeline/.env"
            )

        try:
            cls.conn = _connect_databricks()
        except Exception as e:
            raise RuntimeError(f"Could not connect to Databricks: {e}") from e

        try:
            cls.databricks = _get_databricks_info(cls.conn)
        except Exception:
            cls.conn.close()
            raise

        print(f"\nplayCD CSVs        : {len(cls.playcd)}")
        print(f"Databricks tables  : {len(cls.databricks)}")

    @classmethod
    def tearDownClass(cls):
        if getattr(cls, "conn", None) is not None:
            cls.conn.close()

    def test_table_count_matches(self):
        self.assertEqual(
            len(self.playcd),
            len(self.databricks),
            f"playCD has {len(self.playcd)} tables but Databricks has "
            f"{len(self.databricks)}",
        )

    def test_every_csv_has_databricks_table(self):
        missing = set(self.playcd) - set(self.databricks)
        self.assertFalse(
            missing,
            f"{len(missing)} playCD table(s) have no Databricks table:\n"
            + "\n".join(f"  {t}" for t in sorted(missing)),
        )

    def test_no_extra_databricks_tables(self):
        extra = set(self.databricks) - set(self.playcd)
        self.assertFalse(
            extra,
            f"{len(extra)} Databricks table(s) have no matching playCD CSV:\n"
            + "\n".join(f"  {t}" for t in sorted(extra)),
        )

    def test_row_counts_match(self):
        mismatches = []
        known_diffs = []
        common = set(self.playcd) & set(self.databricks)
        for key in sorted(common):
            playcd_rows = self.playcd[key][0]
            dbx_rows = self.databricks[key][0]
            if playcd_rows != dbx_rows:
                entry = f"  {key}: playCD={playcd_rows}, databricks={dbx_rows}"
                if key in KNOWN_DIFF_TABLES:
                    known_diffs.append(entry)
                else:
                    mismatches.append(entry)

        if known_diffs:
            print(
                f"\n{len(known_diffs)} known table(s) have expected row count "
                f"differences (see 9_scrape_tables README):\n" + "\n".join(known_diffs)
            )

        self.assertFalse(
            mismatches,
            f"{len(mismatches)} table(s) have UNEXPECTED mismatched row counts:\n"
            + "\n".join(mismatches),
        )

    def test_column_counts_match(self):
        mismatches = []
        common = set(self.playcd) & set(self.databricks)
        for key in sorted(common):
            playcd_cols = self.playcd[key][1]
            dbx_cols = self.databricks[key][1]
            if playcd_cols != dbx_cols:
                mismatches.append(
                    f"  {key}: playCD={playcd_cols}, databricks={dbx_cols}"
                )
        self.assertFalse(
            mismatches,
            f"{len(mismatches)} table(s) have mismatched column counts:\n"
            + "\n".join(mismatches),
        )


if __name__ == "__main__":
    unittest.main(verbosity=2)
