[project]
name = "asset-bundles"
version = "0.1.0"
description = "asset-bundles workspace, used locally rather than databricks as it uses it own python env"
requires-python = ">=3.12.12"
dependencies = [
    "chispa>=0.12.0",
    "databricks-sdk>=0.114.0",
    "pyspark>=4.1.2",
    "pytest>=9.0.3",
]
